-- migrate:up
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'groceryclaw_app_runtime') THEN
    CREATE ROLE groceryclaw_app_runtime NOLOGIN;
  END IF;
END
$$;

GRANT groceryclaw_app_user TO groceryclaw_app_runtime;
GRANT USAGE ON SCHEMA public TO groceryclaw_app_runtime;

ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE zalo_users FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_users FORCE ROW LEVEL SECURITY;
ALTER TABLE invite_codes FORCE ROW LEVEL SECURITY;
ALTER TABLE secret_versions FORCE ROW LEVEL SECURITY;
ALTER TABLE inbound_events FORCE ROW LEVEL SECURITY;
ALTER TABLE jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE idempotency_keys FORCE ROW LEVEL SECURITY;
ALTER TABLE pending_notifications FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE canonical_invoices FORCE ROW LEVEL SECURITY;
ALTER TABLE canonical_invoice_items FORCE ROW LEVEL SECURITY;
ALTER TABLE mapping_dictionary FORCE ROW LEVEL SECURITY;
ALTER TABLE product_cache FORCE ROW LEVEL SECURITY;
ALTER TABLE unit_conversions FORCE ROW LEVEL SECURITY;
ALTER TABLE resolved_invoice_items FORCE ROW LEVEL SECURITY;
ALTER TABLE sync_results FORCE ROW LEVEL SECURITY;

COMMIT;

-- migrate:down
BEGIN;

ALTER TABLE sync_results NO FORCE ROW LEVEL SECURITY;
ALTER TABLE resolved_invoice_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE unit_conversions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE product_cache NO FORCE ROW LEVEL SECURITY;
ALTER TABLE mapping_dictionary NO FORCE ROW LEVEL SECURITY;
ALTER TABLE canonical_invoice_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE canonical_invoices NO FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_logs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pending_notifications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE idempotency_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE inbound_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE secret_versions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE invite_codes NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE zalo_users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tenants NO FORCE ROW LEVEL SECURITY;

REVOKE USAGE ON SCHEMA public FROM groceryclaw_app_runtime;
REVOKE groceryclaw_app_user FROM groceryclaw_app_runtime;

COMMIT;
